name: "Build and Deploy to Cachix"

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
              experimental-features = nix-command flakes
              extra-substituters = https://contamination.cachix.org
              extra-trusted-public-keys = contamination.cachix.org-1:KmdW5xVF8ccKEb9tvK6qtEMW+lGa83seGgFyBOkeM/4
    - uses: cachix/cachix-action@v10
      with:
        name: contamination
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
